apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lb7r0rf1g-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/lb7r0rf1g-java-springboot-gitops